services:
  nginx:
    image: nginx:latest
    ports:
      # HOST_PORT:CONTAINER_PORT 
      - "80:80"
    volumes:
      #- hostPath:containerPath:ro
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./style.css:/usr/share/nginx/html/style.css:ro
      - ./about:/usr/share/nginx/html/about:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/usr/share/nginx/html/static:ro
      - ./domain:/usr/share/nginx/html/domain:ro
    networks:
      - proxy_net

  homeservice:
    image: home:0.1
    ports:
      - "8081:8081"
    networks:
      - proxy_net

  inventoryservice:
    image: inventory:0.1
    ports:
      - "8082:8082"
    networks:
      - proxy_net

  orderservice:
    image: order:0.1
    ports:
      - "8083:8083"
    networks:
      - proxy_net

  nodeserver1:
    image: nodeserver:0.1
    environment:
      - PORT=8084
    ports:
      - "8084:8084"
    networks:
      - proxy_net 

  nodeserver2:
    image: nodeserver:0.1
    environment:
      - PORT=8085
    ports:
      - "8085:8085"
    networks:
      - proxy_net 

networks:
  proxy_net:
    name: proxy_net
    driver: bridge
